- Searching and Sorting/Quick Sort/quick sort.py
> Quick Sort

- Searching and Sorting/Bubble Sort/bubble sort.py
> Bubble Sort

- Searching and Sorting/Heap Sort/heap sort.py
> Adding Heap Sort

- Searching and Sorting/Insertion Sort/Insertion Sort.py
Added insertion Sort in Python #12
> Added insertion Sort

- Binary Search.cpp
added a cout statement at line no. 37 for working fine...!
in #9
> add "cout" statements for 'n' numbers

- Searching and Sorting/Bubble Sort/Bubble Sort.cpp
> Added Bubble Sort CPP(C++)

- Greedy Algorithms/Prims/Python/Prims.py
added prims algorithm under greedy agorithm in python language
> add Prims algorithm

- Searching and Sorting/Binary Search/Ruby/binary_search.rb
Closes #34 
Binary search implemented in Ruby.
> Implemented binary search in Ruby. Closes #34

- Searching and Sorting/Cocktail Sort/cocktailSort.py
Added cocktail sort implementation in python.
> Cocktail sort

- LICENSE
- README.md
I've made a few grammatical/spelling fixes to the README and added an MIT LICENSE to the repo. You didn't specify which license you wanted in #31, so I defaulted to MIT, but it can be easily replaced if you so desire. Currently copyright is attributed to your iam-abbas username.
> Update README and add MIT LICENSE file

- SortingAlgos/C++/Merge Sort.cpp
> Added Merge Sort

- Greedy Algorithms/Bellman-Ford.py
1. Create classes for Graph and Vertex.
2. Create a function bellman-ford that takes a Graph object and a source vertex as arguments.
3. A dictionary distance is created with keys as the vertices in the graph and their value all set to infinity.
4. distance[source] is set to 0.
5. The algorithm proceeds by performing an update operation on each edge in the graph n – 1 times. Here n is the number of vertices in the graph.
6. The update operation on an edge from vertex i to vertex j is distance[j] = min(distance[j], distance[i] + weight(i, j)).
7. The dictionary distance is returned.
> Bellman Ford

- SortingAlgos/python/counting_sort.py
- SortingAlgos/python/insertion_sort.py
These algorithms are tested with random values to work with Python 3.7. Type annotations could be removed and they would be usable with Python 2.7 and earlier versions of Python 3.
> Implemented Counting and Insertion Sort Algorithms in Python

- CPU-Scheduling Algorithms/shortest-job-first/C/sjf.c
Shortest Job first cpu scheduling algorithm (with arrival time zero of all processes)  in C language
> sjf scheduling algorithm

- Tree Traversal/C++/BFS.cpp
- Tree Traversal/C++/DFS.cpp
- Tree Traversal/Readme.md
Tree traversal in BFS and DFS manner using adjacency matrix.
> Tree Traversal

- MachineLearning/Perceptron/CPP/main.cpp
- MachineLearning/Perceptron/JavaScript/main.js
It is a type of linear classifier, i.e. a classification algorithm that makes its predictions based on a linear predictor function combining a set of weights with the feature vector.
> Adding perceptron algorithm

- MachineLearning/Perceptron/Python/LinearRegression.py
Linear Regression for Supervised data
> Added Linear Regression algorithm

- Pattern Searching/Robin_Karp.c
I've here written a code to implement the Robin Karp Pattern Searching Algo
max size of input string: 10^5 characters
max pattern size: 1000 characters
> [Pattern Searching] Robin Karp algorithm using C

- Pattern Searching/RabinKarp/rabinKarp.cpp
RabinKarp algo in C++
As I was assigned for this issue.
> Added RabinKarp

- Travelling Salesman Problem/C++/Travelling Salesman Problem.cpp
- Travelling Salesman Problem/C/Travelling Salesman Problem.c
Travelling Salesman Problem in C and C++ #81
> Added Travelling Salesman Problem

- Searching and Sorting/Exponential Search/C++/Exponential Search.cpp
- Searching and Sorting/Exponential Search/Python/Exponential Search.py
Added Exponential Search in C++ and Python #84
> Added Exponential Search

- 2 Stacks in an Array.txt
Added file named '2 Stacks in an Array.txt' which implements 2 stacks in an array. #20
> Add Algorithm 2 Stacks in an Array

- Sorting Algorithm/mergesort.cpp
i didnot saw merge sort in Sorting Algorithm folder
> i am added merge sort in Sorting Algorithm

- Dynamic Programming/kadane algorithm/kadaneAlgo Problem statement.txt
- Dynamic Programming/kadane algorithm/kadanealgo.cpp
Contributing towards issue #96 
Added two files
1) KadaneAlgo Problem statement.txt - contains Maximum subarray problem statement.
2) kadanealgo.cpp -contains a solution for the above problem statement.
> Added two files one contains maximum subarray

- Graph Traversal/BFS/bfs_adjList.c
- Graph Traversal/BFS/bfs_adjMatrix.c
- Graph Traversal/DFS/dfs_adjList.c
- Graph Traversal/DFS/dfs_adjMatrix.c
- Graph Traversal/README.md
Both **BFS** and **DFS** is implemented using **Adjacency Matrix** and **Adjacency List**
> Graph Traversal using BFS and DFS

- Dynamic Programming/0-1 Knapsack/C++/knapsack-problem.cpp
- **Algorithm Name: Knapsack - Dynamic Programming**
- **Language: C++**
> add-c++-knapsack

- Dynamic Programming/Max Product Array/max_product_array.cpp
- **Algorithm Name: Max product array**
- **Language: C++**
> add-c++-max_product_array

- Floyd Cycle Loop Detection/floyd_Cycle_Loop_Detection.cpp
> Added floyd_Cycle_Loop_Detection.cpp

- MaxProductArray/C++/MaxProductArray.cpp
I have added the c++ code for Maximum Product in a given Array.
> MaxProductArrayAdded

- Sorting Algorithm/Heap Sort/C++/heap_sort.cpp
- Sorting Algorithm/Heap Sort/Python/heap_sort.py
Added Heap sort in Python and C++
> Added Heap Sort in Python and C++

- CPU-Scheduling Algorithms/FCFS/Python3/fcfs.py
> FCFS in Python

- Sorting Algorithm/Counting Sort/CountingSort.cpp
Create countingsort cpp 
solved issue #140
> Create countingsort cpp (Issue:#140)

- .gitignore
- Sieve of Eratosthenes/SieveOfEratosthenes.cpp
Added Sieve of Eratosthenes Algorithm written in C++.
> Added Sieve of Eratosthenes

- Dynamic Programming/Maximum size sub square in 2D array/C++/maximum_size_sub_array.cpp
added the working code for the stated problem
> Added DP algorithm to find max size sub square in a 2D matrix of 0s and 1s

- Divide and Conquer/Max Subarray Sum/Python/maxsubarray.py
> Maximum Subarray Sum

- Dynamic Programming/Paths In A Grid/README.md
- Dynamic Programming/Paths In A Grid/paths_in_a_grid.cpp
> added paths in a grid

- Searching and Sorting/Insertion Sort/C++/insertionSort.cpp
Added Insertion Sort Algorithm written in C++.
> Added Insertion Sort Algorithm

- Math/Modular Exponentiation/C++/modular_exponentiation.cpp
> added Modular Exponentation

- ModernCiphers/AES/C++/AES_128_ECB.cpp
Hello!
This new folder contains programs on modern ciphers. I have added a C++ program on Advanced Encryption Standard (128 bits, ECB mode).
Please review the code and suggest modifications.
Thank you.
-Shashwat
> Algorithms for encryption and decryption.

- ModernCiphers/DES/C++/DES.cpp
Please review my program on Data Encryption Standard and suggest modifications.
-Shashwat
> Algorithm for Data Encryption Standard

- Backtracking/m Coloring Problem/Python/mcolor.py
> m Coloring Problem

- Sorting Algorithm/Insertion Sort/C/Insertion_sort.c
Added a program for insertion sort using C
> Added a C program for insertion sort

- Graph Traversal/BFS/bfs.py
> BFS implementation in python

- Dynamic Programming/wine problem/cpp/wine_problem.cpp
Added standard wine problem in Dynamic programming algorithm section
#190
> added wine problem in dynamic programming

- Dynamic Programming/partition problem/cpp/partition_problem.cpp
Added standard Partition problem in Dynamic programming algorithm section
> added partition problem in dynamic programming

- Dijkstra Java Program.txt
This Program implements Dijkstra's Algorithm in Java
> Dijkstra Program

- Remove Superfluous Brackets.txt
This Program removes all superfluous brackets in an expression (C++)
> Remove Superfluous Brackets in Expression

- Stack Algorithms/Span Problem/C++/span.cpp
> Added Span Problem under Stack Algorithms

- Math/Consecutive_Numbers_Sum/consecutive_numbers_sum.cpp
> Add Consecutive Numbers Sum (Math) problem solution

- Sorting Algorithm/Bucket Sort/Bucket sort.cpp
It will handle the negative numbers also.
> Bucket sort updated

- Graphs/graphoperations.c
CreateGraph 
Insert Vertex 
Insert Edge
Delete vertex 
Delete Edge
> Graph operations in c

- Greedy Algorithms/Prims/Prims.c
This algorithm is not available in the repository currently.
Information
Algorithm Name:
Prims in c
Language:
C
> prims in c

- Tower Of Hanoi/TOH.cpp
- Tower Of Hanoi/TOH.java
- Tower Of Hanoi/TOH.py
Tower of Hanoi in Java, C++, Python
> Tower of Hanoi

- CaesarCipher/C++/caesarcipher.cpp
Added code for encryption and decryption of Caesar Cipher
> Added code for CaesarCipher in C++

- Tower of hanoi--C++/TowerOfHanoi.cpp
> Added Sieve of eratosthenes and tower hanoi

- DecimalToBinary.cpp
Decimal to Binary conversion program.
> DecimalToBinary.cpp

- Graphs/hamiltonian cycle.cpp
added hamiltonian cycle in cpp
> adding hamiltonian cycle

- BitwiseOperators.cpp
Bitwise operators program and how they work.
> BitwiseOperators.cpp

- BinaryToDecimal.cpp
Program for converting a binary number to a decimal number
> BinaryToDecimal.cpp

- Vector.cpp
> Vectors.cpp

- selection_sort.cpp
added selection sort in c plus plus
> selectionsort_eastwind.cpp

- primalitytest.cpp
added primality test by miller-rabin algorithm
> primality_eastwind.cpp

- fermatsprime
added prime check by Fermat's algorithm
> fermatsprime_eastwind.cpp

- pollardrho.cpp
added Pollard's Rho algorithm to find a prime factor of composite
> pollardrho_eastwind.cpp

- Linked List/sorted_insertion_LL.cpp
> linked list sorted insertion in cpp

- desktop.ini
- insert_element_into_list.py
added insertion of element into list in python
> adding insertion of element into list

- floyd_warshall_all pair shortest path.cpp
Its an algorithm to find all the shortest paths between all pairs.
> floyd_warshall_all pair shortest path

- graham_scan.cpp
Its an algorithm for Convex Hall.
> graham_scan

- GrahamScan.cpp
Added C++ program for Graham Scan for the convex hull.
> Created GrahamScan.cpp

- Linked List/Adding, Deleting in LL
Program to implement addition and deletion of elements from a linked list.
> Adding, Deleting in LL

- Linked List/doublyLL.c
Implemented doubly linked list. [C code]
> doublyLL.c

- singly linked list/singly limked list.c
> added singly linked list

- Trapping Rain Water
Added a new algorithm, which would be a of great help.
> Trapping Rain Water

- Array Stacking Algorithm/C++/stackusing2qs.cpp
- Insertion_Sort_In_Kotlin.kt
> Addressing issue #143

- BIT/Power of Two/CheckPowerOfTwo.c
- BIT/Power of Two/CheckPowerOfTwo.kt
- BIT/Power of Two/IsPowerOfTwo.py
- BIT/Power of Two/NumberSwapper.java
- BIT/Power of Two/powerOfTwo.cpp
- BIT/Power of Two/powerOfTwo.js
"In mathematics, a power of two is a number of the form 2^n where n is an integer, that is, the result of exponentiation with number two as the base and integer n as the exponent.
In a context where only integers are considered, n is restricted to non-negative values, so we have 1, 2, and 2 multiplied by itself a certain number of times.
Because two is the base of the binary numeral system, powers of two are common in computer science. Written in binary, a power of two always has the form 100…000 or 0.00…001, just like a power of ten in the decimal system." - by Wikipedia.
> Adding a Bit Manipulation Algorithm: Power of two numbers

- LRU Cache Implementation/LRU-Cache-Implementation.cpp
Adding LRU cache implementation in c++.
> LRU Cache Implementation in c++

- Linear search(Recursively).cpp
I have made the code, using linear search  recursively  to find an element in the array.
> Create Linear search(Recursively)

- Kadane's Algorithm.cpp
This algorithm helps to reduce the number of for loops which are used to find the max sub array sum.
> Kadane's Algorithm(used to find the max sub array sum)

- Kotlin/Selection_Sort_In_Kotlin.kt
> Addressing issue #339

- Merge Sort.cpp
This algorithm helps to sort array elements using recursion.
> Merge Sort Algorithm

- Kotlin/Bubble_Sort_In_Kotlin.kt
> Addressing issue #348

- Trapping Rain Water.java
> Added solution for Trapping Rain water problem in java

- Sorting Algorithm/comb_sort.cpp
> Comb_sort.cpp

- Comb-sort
Comb-sort or advanced bubble sort implementation in cpp.
> Comb-sort.cpp

- An Optimal Stopping Problem
This problem can be stated in the following form: Imagine an administrator who wants to hire the best secretary out of n rankable applicants for a position. The applicants are interviewed one by one in random order. A decision about each particular applicant is to be made immediately after the interview. Once rejected, an applicant cannot be recalled. During the interview, the administrator can rank the applicant among all applicants interviewed so far but is unaware of the quality of yet unseen applicants. The question is about the optimal strategy (stopping rule) to maximize the probability of selecting the best applicant.
> Create An Optimal Stopping Problem

- countingSort.cpp
> countSort.cpp

- Two_clique.cpp
C++ program to find out whether a given graph can be converted to two Cliques or not.
> created Two_clique.cpp using c++

- Trapping_rain_Water.cpp
C++ program to find maximum amount of water that can be trapped within given set of bars.
> Created Trapping_Rain_Water.cpp using c++

- C++/FindDuplicate.cpp
N numbers between 1 to N
0(n) time complexity and O(1) space complexity
> FindDuplicate.cpp

- TwoSum/Go/twosum.go
Implemented TwoSum in Go.
Closes #389.
> Added TwoSum implemented in Go

- Stack Algorithms/Balanced Parenthesis Problem/C++/balanced_parenthesis.cpp
Using char stack, checking whether the given string has balanced parenthesis or not. O(n) Time complexity and O(n) space complexity
> Balanced parenthesis problem (using Stack) - C++

- C++/heapSort
issue #433 resolved,Heap sort created.
> issue #433 resolved

- Logistic-Regression
> Logistic regression

- Fibonacci Numbers
This is a basic fibonacci program which is easy to understand. It provides a basic understanding about the fibonacci series,
> Create Fibonacci Numbers

- Kotlin/BinarySearch.kt
#445 Implemented BInary Search in Kotlin
> Binary Search in Kotlin #445

- Fibonacci Numbers using boost library
This program provides the understanding of Fibonacci series. This program also uses boost library which shoud be a MUST for C++ users.
> Create Fibonacci Numbers using boost library

- Greedy Algorithms/Job Sequencing/C++/job_sequencing.cpp
> Added Greedy Algo/Job Sequencing/C++/job_sequencing.cpp

- Greedy Algorithms/Huffman Coding/C++/huffman_coding.cpp
> Added Huffman Coding/C++/huffman_coding.cpp

- Graph Algorithms/Eulerian Graph/C++/eulerian_graph.cpp
> Added Eulerian Graph/C++/eulerian_graph.cpp

- Graph Algorithms/Karger's Algo/C++/Karger_Algo.cpp
> Karger's Algo/C++/Karger_Algo.cpp

- doubly linkedList.cpp
simple example of doubly linked list
> creation of doubly linked list in c++

- Sorting Algorithm/Bitonic Sort/bitonic_sort.cpp
Added this Sort which is better for parallel implementation because we always compare elements in a predefined sequence and the sequence of comparison doesn’t depend on data.
> Bitonic Sort

- Reverse Polish Expression.txt
This Program converts an In-Fix Expression into Reverse Polish Expression in C++
> Reverse Polish Expression

- doubly link/rotate_doublylinkedlist.cpp
Doubly linked list is rotated by p number of nodes which is taken input from the user
> Doubly linked list is rotated

- Balanced Paranthesis.txt
This Program implements Balanced Parenthesis problem in C++
> Balanced Parenthesis

- LCS-DP.cpp
> Longest-common-subsequence.cpp

- Dynamic Programming/Tiling Problem/CPP/Tiling_Problem_bottom_up_dp.cpp
- Dynamic Programming/Tiling Problem/CPP/Tiling_Problem_recursive.cpp
- Dynamic Programming/Tiling Problem/CPP/Tiling_Problem_top_down_dp.cpp
Tiling problem statement, explanation and solution using Recursion, Bottom-Up DP and Top-Down DP
> Dynamic Programming/Tiling Problem/Cpp/Recursive, top-down and bottom-up solutions

- C++/PrimeSeive.cpp
> PrimeSeive.cpp

- Queue with Doubly LL.cpp
- Tower of Hanoi - Java.txt
This Program implements Queue with Doubly Linked List
> Doubly Linked List

- longestIncreasingSubsequence.cpp
This is Longest Increasing Subsequence algorithm using Dynamic programming.
> adding LIS algorithm

- longestCommonSubsequence.cpp
I have solved issue number 398.
> solved issue #398

- Dynamic Programming/Gold Mine Problem
Given a gold mine of n*m dimensions. Each field in this mine contains a positive integer which is the amount of gold in tons. Initially the miner is at first column but can be at any row. the miner can move to the cell diagonally up towards the right or right or diagonally down towards the right. Find out the maximum amount of gold he can collect.
> Create Gold Mine Problem

- C++/Trapping Rain Water
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.
> Create Trapping Rain Water

- Linked List/xor_linked_list.cpp
> Created XOR Linked List

- Tree Traversal/tree_traversal.c
There already existed a .cpp file. I added a .c file.
> C program to traverse trees inorder, post order, preorder

- floydWarshall.cpp
I have solved issue number 282.
> solved issue #282

- insert.py
I have solved issue number 278.
> solved issue #278

- paranthesesChecker.py
> adding balance parantheses

- C/treetraversel.c
Added code for tree travel in c
> Create tree traversel in c

- C++/balanced_parentheses_check.cpp
Solution to balanced parentheses problem
-implemented in c++
-using std::stack
Refers to: #391
> Balanced Parentheses Problem Solution 

- C++/QuickSort-optimised.cpp
> Optimidsed for space

- C++/insertionsort.cpp
Added insertion sort using c++.
> insertion sort added

- merge.c
Merging linked lists in C and related operations
> Merge linked lists

- Balanced Pranthesis stack problem/Balanced_paranthesis_optimized.py
Although the code was already present in this repository.
Added optimized algorithm for checking balanced parenthesis in python 3 which reduces time and space complexity!
> Added optimized code for checking balanced paranthesis in python3

- radix_sort.cpp
I have added the algorithm of radix sort, thanks!
> Created radix_sort.cpp

- Backtracking/Sudoku/sudoku_solver.java
java solution to backtracking problem sodoku added.
> sudoku_solver java solution

- snake_game.cpp
An easy to learn game for beginners. 
With basic fundamental structure.
> Snake Game

- tictactoe.cpp
An easy to learn game for beginners. 
The game is written in C++ and illustrates proper structure for game development.
> Tic Tac Toe game

- Check_Balance_parenthesis.cpp
Parenthesis Balancing is used for checking whether a string contains parenthesis is balanced or not.
> Parenthesis Balancing in C++

- Matching/GaleShapley/galeshapley.cpp
I've implemented the Gale Shapley Algorithm for stable matching of students to companies in C++. My program takes input from the user and prints output in CLI.
> Implemented Gale Shapley Algorithm in cpp

- Python/Johnson_algorithm.py
created Johnson’s algorithm for shortest path in python
> created Johnson’s algorithm in python

- Hash_alg/Hashing_chaining.cpp
- Hash_alg/Hashing_with_chaining.cpp
c++ program to implement hashing with chaining
> Hashing with chaining in c++

- NutBoltWithHashmap.java
**NutsAndBolts Problem Hashmap Implementation in java**
> Added NutsAndBolt Problem Using Hashmap Approach in java

- Lazy Propagation
Lazy Propagation using Binary Indexed Tree.
> Create Lazy Propagation

- Linked List/reverse_k-group_linkedList.cpp
This is an algorithm that will tell how to reverse a linked list in the group of k.
i.e 
Input: 1->2->3->4->5->6->7->8->NULL, K = 3
Output: 3->2->1->6->5->4->8->7->NULL
> Added the k-grouped reverse a linked list algorithm.

- Strings/lexicographicRank.cpp
Given a string, find its rank among all its permutations sorted lexicographically. For example, rank of “abc” is 1, rank of “acb” is 2, and rank of “cba” is 6.
e.g. 
Input : str[] = "acb"
Output : Rank = 2
Input : str[] = "string"
Output : Rank = 598
Input : str[] = "cba"
Output : Rank = 6
> Lexicographic rank of a string

- LIS_in_O(nlogn).cpp
There was already an algorithm in O(n^2) but this is a much faster version with order of complexity n*log(n) .
> Adding longest increasing subsequence in O(nlogn)

- C/MergeSort.cpp
- C/RadixSort.cpp
Added Merge and Radix sort in c.
> Merge and Radix sort in c

- C/insertion.c
- C/selection.c
Added insertion and selection sort program in C language
> insertion and selection sort in C

- Python/HeapSort.py
Added Heap Sort algorithm in python.
> Heapsort.py

- Python/fibonacci.py
program for fibonacci in python language
> fibonacci in python

- Python/RadixSort.py
Added Radix sort algorithm in python.
> Radix sort in python

- Python/dijkstra.py
simple python program for dijkstra algorithm
> dijkstra algorithm in python

- Python/QuickSort.py
Added Quick sort algorithm in python.
> Quick sort in python

- Python/prims_mst.py
program for prims algorithm for minimal spanning tree in python
> prims_mst algorithm in python

- boltAndNUt.java
This is the nut and bolt algorithm in java.
> boltAndNut Algo

- Graph Algorithms/Dinic's Algo/dinic.cpp
> added dinic's algo

- Strings/Suffix Tree.cpp
> Ukkonen's Algorithm

- N-Queens/Python/n-queens.py
I have added N-Queens Problem in Python. Kindly refer to issue #577 .
Waiting for the PR to be merged :)
> added n-queens problem in python

- Lineartimeselectionalgorithm/kthsmallestelement.py
This is selection algorithm which finds kth smallest/largest element in a array with linear time complexity.
> Add this linear time selection algorithm

- Python/invertioncount.py
This is an algorithm to count the the total number of invertions in array.This uses modified merge sort technique to impliment the algorithm in O(log n) time
> Add invertioncount.py to the repository

- Fibonacci Sequence/Fast Fibonacci/Python/fast_fib.py
This is an implementation of a function that calculates the n-th number in the fibonacci sequence in O(log n) time.
The selected language was Python as the answers can be really big and Python has unrestricted integers (other languages have them as libraries and the legibility is not that great).
This PR solves issue #584.
> Add fast fibonacci implementation in Python

- Python/fibonacci.py
Added fibonacci matrix multiplication approach implementation on python
> add fibonacci matrix mult implementation O(log(N))

- Python/kth_element.py
> Kth largest element

- Graph Algorithms/maximum_network_flow.py
This is an implementation of ford fulkerson algorithm in python.
This PR closes #596
> Add maximum_network_flow.py to the repo

- Python/Multilevel-Feedback-Queue.py
Multilevel Feedback Queue implemented in python.
> Multi Level Feedback Queue Scheduling Algorithm #437

- Divide and Conquer/KaratsubaFastMultiplication.cpp
Add this Karatsuba Fast Multiplication Algorithm which uses Divide and Conquer Method. This closes #603 .
> KaratsubaFastMultiplication.cpp

- MonkeySort/monkeySort.js
Learn the worst sorting Algorithm :D
> monkey sort

- Math/Sieve of Eratosthenes/golang/sieveOfErathosthenes.go
sieve code in golang added in Math/Sieve of Eratosthenes/golang
> Sieve of Erathosthenes code added in golang

- catalan.cpp
> Catalan number program added

- Math/EulerTotientFunction/eulerFunction.cpp
euler totient code added in c++
> euler totient function added

- stack-implementtation.py
> stack implementation using python

- Balanced Pranthesis stack problem/Parenthesis_check (using C)
Added a C code for balanced parenthesis check
> Balanced_Parenthesis_check

- Convex HULL/monotone.cpp
- Convex HULL/readme.md
Adding some algorithm i.e. Convex HULL
> Convex Algorithm

- C++/RegexMatching.cpp
> added regex matching

- prime number
This program gives all the prime numbers till the given number.
> Gives Prime Numbers

- Clock Sort
Sorts given array of integers in ascending order using clock sort and shows the time taken for sorting. Also contains merge sort function.
> Clock Sort

- gcd and lcm
Gives greatest common divisor and least common multiple of 2 numbers.
> Create gcd and lcm

- Kotlin/heap_sort_in_kotlin.kt
> heap_sort_in_kotlin.kt

- Kotlin/quick_sort_in_kotlin
> quick_sort_in_kotlin

- Kotlin/count_sort_in_kotlin
> count_sort_in_kotlin

- Kotlin/binary_search_in_kotlin.kt
> binary_search_in_kotlin.kt

- Python/cosine_similarity.py
for example of cosine similarity in vector
> add Python/cosine_similarity.py 

- Dynamic Programming/Count_all_possible_BST/c++/count_all_BSTs.cpp
Added **count_all_possible_BST** algorithm in Dynamic Programming section in **C++** language.
> added allPossibleBST program

- Array Reversal.c
Given an array, of size **n**, reverse it.
> Array Reversal.c

- Java/binarySerach.java
This file is related to issue #687
> Added "binary Search" algorithm in JAVA

- Java/BubbleSort.java
This file is related to issue #690
> Added "Bubble Sort" Algorithm in Java in Java Directory

- Go/BinarySearch.go
This file is related to issue #692
> Added new directory 'Go' for algorithms in golang and added "Binary Search" Algorithm in Golang in Go Directory

- Go/BubbleSort.go
This file is related to issue #694
> Added "Bubble Sort" Algorithm Golang in Go Directory

- Go/countinversion.go
This file is related to issue #696
> Added "Counting inversion" Algorithm Golang in Go Directory

- Go/Dijkstra.go
This file is related to issue #698
> Added "Djkistra" Algorithm Golang in Go Directory

- Go/fibonacciSeries.go
This file is related to issue #700
> Added "FibonacciSeries" Algorithm Golang in Go Directory

- Go/FlyodsAlgorithm.go
this file is related to issue #702
> Added "FloydsAlgorithm" Algorithm Golang in Go Directory

- Go/GCDEuclidean.go
this file is related to issue #704
> Added "Eucledian GCD" Algorithm in Golang in Go Directory

- Go/hammingDistance.go
> Added "Hamming Distance" Algorithm in Golang in Go Directory

- Go/HeapSort.go
> Added "Heap Sort" Algorithm in Golang in Go Directory

- Go/InsertionSort.go
> Added "Insertion Sort" Algorithm in Golang in Go Directory

- Go/Kadanes.go
> Added "Kadanes Algorithm" in Golang in Go Directory

- Go/linear_search.go
> Added "Linear Search Algorithm" in Golang in Go Directory

- Go/merge_sort.go
> Added "Merge Sort Algorithm" in Golang in Go Directory

- Python/binary-search.py
> binary-search-python

- LongestCommonSubsequence/C++/Longest_common_subsequence.cpp
- LongestCommonSubsequence/longest-common-subsequence.java
longest common subsequence done ! kindly review it
> longest-common-subsequence-implementation

- Recursive/gcd.py
- Recursive/n_choose_k.py
Here, I added 2 recursive algorithm:
- GCD algorithm to compute the greatest common divisor between two integers
- N Choose K algorithm to compute the binomial coefficient C(N, K) between two integers
> Recursive algorithm

- Recursive/knapsack_algorithm.py
added algorithm to know how we get the maximum value (i), given our knapsack just can hold a maximum weight of W.
> add example of knapsack 0-1 algorithm

- C++/recursion/CPP - Merge Sort.cpp
- C++/recursion/CPP - Recursion - Linear Search.cpp
- C++/recursion/QuickSort.cpp
- C++/recursion/Randomized Quicksort.cpp
- C++/recursion/Tower of Hanoi.cpp
- C++/recursion/bubbleSort.cpp
- C++/recursion/fastpower.cpp
- C++/recursion/random_no_generator.cpp
> added recursion and backtracking

- Graph Algorithms/detectcycleingraph.py
This is an Dfs approach to detect cycle in a graph using python.
> Add detectcycleingraph.py

- Divide and Conquer/Median of Arrays/medianofmedians.cpp
Given an array and a number k where k is smaller than the size of the array, we need to find the k’th smallest element in the given array. It is given that all array elements are distinct.At that case this worst case linear time algo can be used.
> add medianofmedian.cpp

- Graphs/jhonsonshortestpathalgo.py
This is simple python implimentation of jhonsons shortest path algo.This closes #523
> Add jhonsonshortestalgo.py

- Graph Algorithms/closestpairofpoints.py
Closest Pair of Points in Python
> closestpairofpoints.py

- C++/dijkstras.cpp
Dijkstra's algorithm #199 issue solved
> Adding Dijkstra's Algorithm

- Java/Graph/BFS and DFS.java
- Linked List/README.md
added BFS and DFS graph traversal in Java using both adjacency list and matrix
>  BFS and DFS using adjacency list and matrix 

- C++/catalanNumbers.cpp
> adding catalanNumbers.cpp 

- Graph Algorithms/floodfillalgo.py
Add flood fill algorithm implimentation to change color of graph in python.
> Floodfillalgo.py

- Greedy Algorithms/machineselect.py
Greddy approach to select machine to schedule a minmal max span length.
> Machineselect.py

- Strings/robbinkarpstringmatching.py
Add robbin karp string matching algo implimented in python.
> robbinkarpstringmatching.py

- naivestringmatching.py
> naivestringmatching.py

- Strings/kmpstringmatching.py
This is an implimentation of kmp string matching algo in python.
> kmpstringmatching.py

- studentstructure.cpp
A structure of student information in cpp.
> studentstructure.cpp

- Queue/queueusingclass.cpp
A queue data structure implementation using class.
> queueusingclass.cpp

- bookclass.cpp
A book information container object created using class.
> bookclass.cpp

- Dynamic Programming/matrixchainmultiplication.py
Dynamic Programming Python implementation of Matrix Chain Multiplication.
> matrixchainmultiplication.py

- weightedjobscheduling.cpp
Given some jobs with its start time,finish time and profit.we have to maximize the profit.
> weightedjobscheduling.cpp

- exchangingmoney.cpp
A problem similar type of coin change problem
> Add exchangemoney.cpp

- CPU-Scheduling Algorithms/sjfmultiprocessing.py
Creating processes using multi programming in python which can scheduled in shortest job first manner.
> Add sjfmultiprocessing.py

- Graph Algorithms/isbipartite.py
Python program to check a graph is bipartite or not.
> isbipartite.py

- Graph Algorithms/maximumbipartitematching.py
A python implementation of maximum bipartite matching.
> maximumbipartitematching.py

- Dynamic Programming/shotestcommonsupersequence.py
A dynamic programming based C program to  find length of the shortest super sequence.
> shotestcommonsupersequence.py

- Dynamic Programming/wordbreakingproblem.cpp
A cpp solution of word breaking problem solution.
> wordbreakingproblem.cpp

- Dynamic Programming/dicethrow.py
A python solution of dice throw problem.
> dicethrow.py

- searcharray.cpp
Searching a element in a array.
> searcharray.cpp

- Balanced-Unbalanced-exp.py
Check if the given Expression is balanced or unbalanced using Stack- Data Structure.
Ex: {()} -> Balanced Expression
{[)]{ -> Unbalanced Expression
> Balanced and Unbalanced Expressions using Stack
